CREATE PROCEDURE `INSERT_T_RESPONSE`(
    IN I_SESSION_ID CHAR(36),
    IN I_ROLE VARCHAR(20),       
    IN I_MESSAGE VARCHAR(255),   
    IN I_JOY INT,
    IN I_LOVE INT,
    IN I_SAD INT,
    IN I_ANGER INT,
    IN I_ERROR INT
)
BEGIN
    INSERT INTO T_RESPONSE 
        (SESSION_ID, ROLE, MESSAGE, JOY, LOVE, SAD, ANGER, INS_DATETIME, ERROR_FLG)
    VALUES 
        (I_SESSION_ID, I_ROLE, I_MESSAGE, I_JOY, I_LOVE, I_SAD, I_ANGER, CURRENT_TIMESTAMP(), I_ERROR);
END