CREATE PROCEDURE `SELECT_T_RESPONSE`(
    IN I_SESSION_ID CHAR(36)
)
BEGIN
    SELECT ROW_NUMBER() OVER (ORDER BY RESPONSE_ID) AS ROW_NUM,
           ROLE,
           MESSAGE,
           JOY,
           LOVE,
           SAD,
           ANGER
    FROM T_RESPONSE 
    WHERE SESSION_ID = I_SESSION_ID
      AND ERROR_FLG = 0
    ORDER BY INS_DATETIME;
END