-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GptGameWeb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GptGameWeb` ;

-- -----------------------------------------------------
-- Schema GptGameWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GptGameWeb` DEFAULT CHARACTER SET utf8 ;
USE `GptGameWeb` ;

-- -----------------------------------------------------
-- Table `GptGameWeb`.`M_SESSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GptGameWeb`.`M_SESSION` ;

CREATE TABLE `M_SESSION` (
  `SESSION_ID` char(36) NOT NULL COMMENT 'セッションID',
  `INS_DATETIME` datetime DEFAULT NULL COMMENT '登録日時',
  PRIMARY KEY (`SESSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GptGameWeb`.`T_RESPONSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GptGameWeb`.`T_RESPONSE` ;

CREATE TABLE `T_RESPONSE` (
  `RESPONSE_ID` int NOT NULL AUTO_INCREMENT COMMENT '応答ID（連番）',
  `SESSION_ID` char(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT 'セッションID',
  `ROLE` varchar(20) NOT NULL COMMENT 'gptのロール',
  `MESSAGE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '送信値／応答値',
  `JOY` int DEFAULT NULL COMMENT '感情：喜び',
  `LOVE` int DEFAULT NULL COMMENT '感情：愛',
  `SAD` int DEFAULT NULL COMMENT '感情：悲しみ',
  `ANGER` int DEFAULT NULL COMMENT '感情：怒り',
  `INS_DATETIME` datetime DEFAULT NULL COMMENT '登録日時',
  `ERROR_FLG` bit(1) DEFAULT b'0' COMMENT 'エラーフラグ',
  PRIMARY KEY (`RESPONSE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=775 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
