CREATE TABLE `M_SESSION` (
  `SESSION_ID` char(36) NOT NULL COMMENT 'セッションID',
  `INS_DATETIME` datetime DEFAULT NULL COMMENT '登録日時',
  PRIMARY KEY (`SESSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci