CREATE TABLE `T_RESPONSE` (
  `RESPONSE_ID` int NOT NULL AUTO_INCREMENT COMMENT '応答ID（連番）',
  `SESSION_ID` char(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT 'セッションID',
  `ROLE` varchar(20) NOT NULL COMMENT 'gptのロール',
  `MESSAGE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '送信値／応答値',
  `JOY` int DEFAULT NULL COMMENT '感情：喜び',
  `LOVE` int DEFAULT NULL COMMENT '感情：愛',
  `SAD` int DEFAULT NULL COMMENT '感情：悲しみ',
  `ANGER` int DEFAULT NULL COMMENT '感情：怒り',
  `INS_DATETIME` datetime DEFAULT NULL COMMENT '登録日時',
  `ERROR_FLG` bit(1) DEFAULT b'0' COMMENT 'エラーフラグ',
  PRIMARY KEY (`RESPONSE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=947 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci